FROM ubuntu:20.04
LABEL maintainer="Chun-Jie Liu <chunjie.sam.liu@gmail.com>"
LABEL Description="This image is used for running Kallisto RNA seq qauntification tool "

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential cmake zlib1g-dev libhdf5-dev

#install git
RUN apt-get install --yes git

RUN git clone https://github.com/pachterlab/kallisto.git \
  && cd kallisto \
  && git checkout v0.50.0  \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install

ENTRYPOINT ["kallisto"]