
FROM mambaorg/micromamba:1.5.6
LABEL maintainer="Chun-Jie Liu <chunjie.sam.liu@gmail.com>"
# kallisto.salmon.cufflinks

ARG MAMBA_DOCKERFILE_ACTIVATE=1

ARG DEBIAN_FRONTEND=noninteractive

COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml

# RUN apt update && apt install -y build-essential cmake zlib1g-dev libhdf5-dev wget git

RUN micromamba install -y -n base -f /tmp/env.yaml && micromamba clean --all --yes

RUN git clone https://github.com/pachterlab/kallisto.git \
  && cd kallisto \
  && git checkout v0.50.0  \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install

ENV PATH /opt/conda/bin/:$PATH