FROM ubuntu:20.04
LABEL maintainer="Chun-Jie Liu <chunjie.sam.liu@gmail.com>"
LABEL Description="This image is used for running Kallisto RNA seq qauntification tool "

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential cmake zlib1g-dev libhdf5-dev wget git



RUN git clone https://github.com/pachterlab/kallisto.git \
  && cd kallisto \
  && git checkout v0.50.0  \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install

RUN wget https://github.com/samtools/samtools/releases/download/1.19/samtools-1.19.tar.bz2 \
  && tar -vxjf samtools-1.19.tar.bz2 \
  && cd samtools-1.19 \
  && make \
  && make install

ENTRYPOINT ["kallisto"]